name       : xsettingsd
version    : 1.0.2
release    : 1
source     :
    - https://github.com/derat/xsettingsd/archive/v1.0.2.tar.gz : 69b5d1987608d1b5f2a0085f2f88cc55936a99b92279118e655d665ebb5e50d3
license    : BSD-3-Clause
component  : system.utils
summary    : Provides settings to X11 applications via the XSETTINGS specification
description: |
    Provides settings to X11 applications via the XSETTINGS specification
builddeps  :
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
